# Generated by Django 2.2.5 on 2019-10-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('website', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('pwd', models.CharField(max_length=128)),
                ('time_add', models.DateTimeField(auto_now_add=True, null=True)),
                ('time_modify', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'password_tab',
            },
        ),
    ]
